[feature] Add task parameters popup on task run
CaptainJNS/rakeman pull request #6
Opened 2020-11-29 20:59 UTC by olehvolynets

https://trello.com/c/KVKtMyx8

2020-11-30 16:11 UTC, CaptainJNS requested changes

2020-11-30 16:11 UTC, CaptainJNS commented on db/migrate/20201129193419_add_parameter_position_to_task_parameter.rb
> +    add_column :rakeman_task_parameters, :parameter_position, :integer, default: 0
I've thought that position of parameters will depend on their creation time. Need to discuss.
Add a data migration If this will stay as you wrote

2020-11-30 16:11 UTC, CaptainJNS commented on lib/generators/rakeman/templates/initializer.rb
> +require 'rakeman'
why?

2020-11-30 16:11 UTC, CaptainJNS commented on db/migrate/20201129193419_add_parameter_position_to_task_parameter.rb
> +    add_column :rakeman_task_parameters, :parameter_position, :integer, default: 0
Why not just `position`?

2020-11-30 16:11 UTC, CaptainJNS commented on spec/models/rakeman/task_parameter_spec.rb
> +    it { is_expected.to have_db_column(:parameter_position) }
```suggestion
    it { is_expected.to have_db_column(:parameter_position).with_options(default: 0) }
```

2020-11-30 16:11 UTC, CaptainJNS commented on .rubocop.yml
> +  Enabled: false
Please separate expectations in unit tests. You can disable this lint for feature tests

2020-11-30 16:11 UTC, CaptainJNS commented on app/controllers/rakeman/rake_tasks_controller.rb
> +    Rakeman::Web::Tasks::Run.call(task, params, manager)
Please pass only `params`, and then in `Rakeman::Web::Tasks::Run` find task by `params[:id]` and create new `manager`

2020-11-30 16:11 UTC, CaptainJNS commented on app/services/rakeman/web/tasks/run.rb
> +# frozen_string_literal: true
```ruby
module Rakeman
  module Web
    module Tasks
      class Run
        extend Rakeman::Lib::Callable

        def initialize(params)
          @task_id = params[:id]
          @task_parameters = params[:task_parameters].to_h
        end

        def call
          return unless task && task_parameters

          manager.execute(task, passed_params)
        end

        private

        def task
          @task ||= Rakeman::RakeTask.find_by(id: @task_id)
        end

        def task_parameters
          @task_parameters ||= task.params.find(@task_parameters.keys).sort_by(&:parameter_position)
        rescue ActiveRecord::RecordNotFound
          nil
        end

        def passed_params
          @passed_params ||= @task_parameters.map { |parameter| @params[parameter.id.to_s] }
        end

        def manager
          @manager ||= Rakeman::Manager.new
        end
      end
    end
  end
end
```

2020-11-30 16:11 UTC, CaptainJNS commented on config/routes.rb
>    get 'rake_tasks/update_list', to: 'rake_tasks#update_tasks_list', as: 'update_tasks_list'
Can you please update all `get`s to `post`s?

2020-11-30 16:11 UTC, CaptainJNS commented on app/controllers/rakeman/rake_tasks_controller.rb
>      redirect t('rakeman.tasks.events.executed')
what if task will not be executed?

2020-11-30 16:11 UTC, CaptainJNS commented on spec/services/rakeman/web/tasks/run_spec.rb
> +      expect(service.call).to be_truthy
useless

2020-11-30 16:11 UTC, CaptainJNS commented on spec/services/rakeman/web/tasks/run_spec.rb
> +      expect(service.call).to be_falsey
same

2020-12-02 08:34 UTC, olehvolynets commented on db/migrate/20201129193419_add_parameter_position_to_task_parameter.rb
> +    add_column :rakeman_task_parameters, :parameter_position, :integer, default: 0
position may potentially interfere with gems like act_as_list

2020-12-14 08:21 UTC, olehvolynets commented on lib/generators/rakeman/templates/initializer.rb
> +require 'rakeman'
moved it from application.rb

2020-12-27 16:57 UTC, olehvolynets commented on app/controllers/rakeman/rake_tasks_controller.rb
>      redirect t('rakeman.tasks.events.executed')
nothing is gonna happen

2020-12-27 18:36 UTC, olehvolynets commented on .rubocop.yml
> +  Enabled: false
Makes no sense, only will increase test time

2021-03-03 12:26 UTC, CaptainJNS approved these changes

2021-03-03 12:26 UTC, CaptainJNS commented on Gemfile
> +gem 'pry', '~> 0.13.1'
why not in gemspec?

2023-04-19 19:36 UTC, closed without merging